# src/Ram/SavonBundle/Resources/config/routing.yml

ram_accueil:
    path:      /accueil
    defaults: { _controller: RamSavonBundle:Accueil:index}

# ========================================================

ram_produit_home:
    path:      /produit/{page}
    defaults: { _controller: RamSavonBundle:Produit:index, page: 1}
    requirements:
        page: \d*

ram_produit_view:
    path:      /produit/view/{produit_id}
    defaults:  { _controller: RamSavonBundle:Produit:view }
    requirements:
        produit_id: \d+

ram_produit_add:
    path:      /produit/add
    defaults:  { _controller: RamSavonBundle:Produit:add }

ram_produit_edit:
    path:      /produit/edit/{produit_id}
    defaults:  { _controller: RamSavonBundle:Produit:edit }
    requirements:
        produit_id: \d+

ram_produit_delete:
    path:      /produit/delete/{produit_id}
    defaults:  { _controller: RamSavonBundle:Produit:delete }
    requirements:
        produit_id: \d+

# ========================================================

ram_recette_home:
    path:      /recette/{page}
    defaults: { _controller: RamSavonBundle:Recette:index, page: 1}
    requirements:
        page: \d*

ram_recette_view:
    path:      /recette/view/{recette_id}
    defaults:  { _controller: RamSavonBundle:Recette:view }
    requirements:
        recette_id: \d+

ram_recette_add:
    path:      /recette/add
    defaults:  { _controller: RamSavonBundle:Recette:add }

ram_recette_edit:
    path:      /recette/edit/{recette_id}
    defaults:  { _controller: RamSavonBundle:Recette:edit }
    requirements:
        recette_id: \d+

ram_recette_delete:
    path:      /recette/delete/{recette_id}
    defaults:  { _controller: RamSavonBundle:Recette:delete }
    requirements:
        recette_id: \d+

# ===========================================================

ram_ingredient_home:
    path:      /ingredient/{page}
    defaults: { _controller: RamSavonBundle:Ingredient:index, page: 1}
    requirements:
        page: \d*

ram_ingredient_view:
    path:      /ingredient/view/{ingredient_id}
    defaults:  { _controller: RamSavonBundle:Ingredient:view }
    requirements:
        ingredient_id: \d+

ram_ingredient_add:
    path:      /ingredient/add
    defaults:  { _controller: RamSavonBundle:Ingredient:add }

ram_ingredient_edit:
    path:      /ingredient/edit/{ingredient_id}
    defaults:  { _controller: RamSavonBundle:Ingredient:edit }
    requirements:
        ingredient_id: \d+

ram_ingredient_delete:
    path:      /ingredient/delete/{ingredient_id}
    defaults:  { _controller: RamSavonBundle:Ingredient:delete }
    requirements:
        ingredient_id: \d+

# ===========================================================

ram_recette_ingredient_home:
    path:      /recette_ingredient/{page}
    defaults: { _controller: RamSavonBundle:RecetteIngredient:index, page: 1}
    requirements:
        page: \d*

ram_recette_ingredient_view:
    path:      /recette_ingredient/view/{recette_id}/{ingredient_id}
    defaults:  { _controller: RamSavonBundle:RecetteIngredient:view }
    requirements:
        recette_id: \d+
        ingredient_id : \d+

ram_recette_ingredient_add:
    path:      /recette_ingredient/add
    defaults:  { _controller: RamSavonBundle:RecetteIngredient:add }

ram_recette_ingredient_edit:
    path:      /recette_ingredient/edit/{recette_id}/{ingredient_id}
    defaults:  { _controller: RamSavonBundle:RecetteIngredient:edit }
    requirements:
        recette_id: \d+
        ingredient_id : \d+

ram_recette_ingredient_delete:
    path:      /recette_ingredient/delete/{recette_id}/{ingredient_id}
    defaults:  { _controller: RamSavonBundle:RecetteIngredient:delete }
    requirements:
        recette_id: \d+
        ingredient_id : \d+