# src/Ram/SavonBundle/Resources/config/routing.yml

ram_accueil:
    path:      /accueil
    defaults: { _controller: RamSavonBundle:Accueil:index}

# ========================================================

ram_produit_home:
    path:      /produit/{page}
    defaults: { _controller: RamSavonBundle:Produit:index, page: 1}
    requirements:
        page: \d*

ram_produit_view:
    path:      /produit/view/{produit_id}
    defaults:  { _controller: RamSavonBundle:Produit:view }
    requirements:
        produit_id: \d+

ram_produit_add:
    path:      /produit/add
    defaults:  { _controller: RamSavonBundle:Produit:add }

ram_produit_edit:
    path:      /produit/edit/{produit_id}
    defaults:  { _controller: RamSavonBundle:Produit:edit }
    requirements:
        produit_id: \d+

ram_produit_delete:
    path:      /produit/delete/{produit_id}
    defaults:  { _controller: RamSavonBundle:Produit:delete }
    requirements:
        produit_id: \d+

# ========================================================

ram_recette_home:
    path:      /recette/{page}
    defaults: { _controller: RamSavonBundle:Recette:index, page: 1}
    requirements:
        page: \d*

ram_recette_view:
    path:      /recette/view/{id}
    defaults:  { _controller: RamSavonBundle:Recette:view }
    requirements:
        id: \d+

ram_recette_add:
    path:      /recette/add
    defaults:  { _controller: RamSavonBundle:Recette:add }

ram_recette_edit:
    path:      /recette/edit/{id}
    defaults:  { _controller: RamSavonBundle:Recette:edit }
    requirements:
        id: \d+

ram_recette_delete:
    path:      /recette/delete/{id}
    defaults:  { _controller: RamSavonBundle:Recette:delete }
    requirements:
        id: \d+

# ===========================================================

ram_ingredient_home:
    path:      /ingredient/{page}
    defaults: { _controller: RamSavonBundle:Ingredient:index, page: 1}
    requirements:
        page: \d*

ram_ingredient_view:
    path:      /ingredient/view/{id}
    defaults:  { _controller: RamSavonBundle:Ingredient:view }
    requirements:
        id: \d+

ram_ingredient_add:
    path:      /ingredient/add
    defaults:  { _controller: RamSavonBundle:Ingredient:add }

ram_ingredient_edit:
    path:      /ingredient/edit/{id}
    defaults:  { _controller: RamSavonBundle:Ingredient:edit }
    requirements:
        id: \d+

ram_ingredient_delete:
    path:      /ingredient/delete/{id}
    defaults:  { _controller: RamSavonBundle:Ingredient:delete }
    requirements:
        id: \d+

# ===========================================================

ram_composition_home:
    path:      /composition/{page}
    defaults: { _controller: RamSavonBundle:Composition:index, page: 1}
    requirements:
        page: \d*

ram_composition_view:
    path:      /composition/view/{id}
    defaults:  { _controller: RamSavonBundle:Composition:view }
    requirements:
        id: \d+

ram_composition_add:
    path:      /composition/add
    defaults:  { _controller: RamSavonBundle:Composition:add }

ram_composition_edit:
    path:      /composition/edit/{id}
    defaults:  { _controller: RamSavonBundle:Composition:edit }
    requirements:
        id: \d+

ram_composition_delete:
    path:      /composition/delete/{id}
    defaults:  { _controller: RamSavonBundle:Composition:delete }
    requirements:
        id: \d+