# src/Ram/SavonBundle/Resources/config/routing.yml

ram_accueil:
    path:      /accueil
    defaults: { _controller: RamSavonBundle:Accueil:index}

# ========================================================

ram_produit_home:
    path:      /produit/{page}
    defaults: { _controller: RamSavonBundle:Produit:index, page: 1}
    requirements:
        page: \d*

ram_produit_view:
    path:      /produit/view/{produit_id}
    defaults:  { _controller: RamSavonBundle:Produit:view }
    requirements:
        produit_id: \d+

ram_produit_add:
    path:      /produit/add
    defaults:  { _controller: RamSavonBundle:Produit:add }

ram_produit_edit:
    path:      /produit/edit/{produit_id}
    defaults:  { _controller: RamSavonBundle:Produit:edit }
    requirements:
        produit_id: \d+

ram_produit_delete:
    path:      /produit/delete/{produit_id}
    defaults:  { _controller: RamSavonBundle:Produit:delete }
    requirements:
        produit_id: \d+

# ========================================================

ram_recette_home:
    path:      /recette/{page}
    defaults: { _controller: RamSavonBundle:Recette:index, page: 1}
    requirements:
        page: \d*

ram_recette_view:
    path:      /recette/view/{recette_id}
    defaults:  { _controller: RamSavonBundle:Recette:view }
    requirements:
        recette_id: \d+

ram_recette_add:
    path:      /recette/add
    defaults:  { _controller: RamSavonBundle:Recette:add }

ram_recette_edit:
    path:      /recette/edit/{recette_id}
    defaults:  { _controller: RamSavonBundle:Recette:edit }
    requirements:
        recette_id: \d+

ram_recette_delete:
    path:      /recette/delete/{recette_id}
    defaults:  { _controller: RamSavonBundle:Recette:delete }
    requirements:
        recette_id: \d+

# Ingrédients
ram_recette_ingredient_add:
    path:      /recette/ingredient_add
    defaults:  { _controller: RamSavonBundle:Recette:addIngredient }

ram_recette_ingredient_edit:
    path:      /recette/ingredient_edit/{recette_id}/{ingredient_id}
    defaults:  { _controller: RamSavonBundle:Recette:editIngredient }
    requirements:
        recette_id: \d+
        ingredient_id : \d+

ram_recette_ingredient_delete:
    path:      /recette/ingredient_delete/{recette_id}/{ingredient_id}
    defaults:  { _controller: RamSavonBundle:Recette:deleteIngredient }
    requirements:
        recette_id: \d+
        ingredient_id : \d+

# charts
ram_recette_ingredient_charts:
    path:      /recette/ingredient/charts/{recette_id}
    defaults:  { _controller: RamSavonBundle:Recette:charts}
    requirements:
        recette_id: \d+

# ===========================================================

ram_ingredient_home:
    path:      /ingredient/{page}
    defaults: { _controller: RamSavonBundle:Ingredient:index, page: 1}
    requirements:
        page: \d*

ram_ingredient_view:
    path:      /ingredient/view/{ingredient_id}
    defaults:  { _controller: RamSavonBundle:Ingredient:view }
    requirements:
        ingredient_id: \d+

ram_ingredient_add:
    path:      /ingredient/add
    defaults:  { _controller: RamSavonBundle:Ingredient:add }

ram_ingredient_edit:
    path:      /ingredient/edit/{ingredient_id}
    defaults:  { _controller: RamSavonBundle:Ingredient:edit }
    requirements:
        ingredient_id: \d+

ram_ingredient_delete:
    path:      /ingredient/delete/{ingredient_id}
    defaults:  { _controller: RamSavonBundle:Ingredient:delete }
    requirements:
        ingredient_id: \d+

# ===========================================================

ram_serie_home:
    path:      /serie/{page}
    defaults: { _controller: RamSavonBundle:Serie:index, page: 1}
    requirements:
        page: \d*

ram_serie_view:
    path:      /serie/view/{serie_id}
    defaults:  { _controller: RamSavonBundle:Serie:view }
    requirements:
        serie_id: \d+

ram_serie_add:
    path:      /serie/add
    defaults:  { _controller: RamSavonBundle:Serie:add }

ram_serie_edit:
    path:      /serie/edit/{serie_id}
    defaults:  { _controller: RamSavonBundle:Serie:edit }
    requirements:
        serie_id: \d+

ram_serie_delete:
    path:      /serie/delete/{serie_id}
    defaults:  { _controller: RamSavonBundle:Serie:delete }
    requirements:
        serie_id: \d+

# Ingrédients
ram_serie_ingredient_add:
    path:      /serie/ingredient_add
    defaults:  { _controller: RamSavonBundle:Serie:addIngredient }

ram_serie_ingredient_edit:
    path:      /serie/ingredient_edit/{serie_id}/{ingredient_id}
    defaults:  { _controller: RamSavonBundle:Serie:editIngredient }
    requirements:
        serie_id: \d+
        ingredient_id : \d+

ram_serie_ingredient_delete:
    path:      /serie/ingredient_delete/{serie_id}/{ingredient_id}
    defaults:  { _controller: RamSavonBundle:Serie:deleteIngredient }
    requirements:
        serie_id: \d+
        ingredient_id : \d+

# charts
ram_serie_ingredient_charts:
    path:      /serie/ingredient/charts/{serie_id}
    defaults:  { _controller: RamSavonBundle:Serie:charts}
    requirements:
        serie_id: \d+