services:
#    ram_savon.example:
#        class: Ram\SavonBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    ram_savon.antispam:
        class: Ram\SavonBundle\Antispam\RamAntispam
        arguments: [@mailer, 10]
        tags:
            -  { name: twig.extension }
        calls:
            - [ setLocale, [ %locale% ] ]

    ram_savon.ckeditor:
        class: Ram\SavonBundle\Form\Type\CkeditorType
        tags:
            - { name: form.type, alias: ckeditor }

    ram_savon.beta.html:
        class: Ram\SavonBundle\Beta\BetaHTML

    ram_savon.beta.listener:
        class: Ram\SavonBundle\Beta\BetaListener
        arguments: [@ram_savon.beta.html, "2013-10-20"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta }
            - { name: kernel.event_listener, event: kernel.controller, method: ignoreBeta }