ram_user:
    resource: "@RamUserBundle/Resources/config/routing.yml"
    prefix:   /

ram_savon:
    resource: "@RamSavonBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: RamUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout