# app/config/security.yml

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        #Ram\UserBundle\Entity\User: plaintext
        Ram\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        #in_memory:
        #    memory:
        #        users:
        #            user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #            admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main:
            entity:
                class:    Ram\UserBundle\Entity\User
                property: username
    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:   ^/
            anonymous: true
            #provider:  in_memory
            provider : main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: /accueil
            remember_me:
                key:        %secret% # %secret% est un paramètre de parameters.yml
    access_control:
        - { path: ^/\w+/(delete|edit), roles: ROLE_ADMIN }
        - { path: ^/\w+/add, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }