<?php

namespace Ram\SavonBundle\Entity;

/**
 * RecetteIngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecetteIngredientRepository extends \Doctrine\ORM\EntityRepository
{
}
