<?php

namespace Ram\SavonBundle\Entity;

/**
 * RecetteEtapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecetteEtapeRepository extends \Doctrine\ORM\EntityRepository
{
}
