<?php

namespace Ram\SavonBundle\Entity;

/**
 * SerieIngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieIngredientRepository extends \Doctrine\ORM\EntityRepository
{
}
