<?php

namespace Ram\SavonBundle\Entity;

/**
 * SerieEtapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieEtapeRepository extends \Doctrine\ORM\EntityRepository
{
}
